### ISSUE TITLE
Improve navbar design

### ISSUE THREAD

**Issue by Rakshit-gen** [Rakshit-gen/Slanine#1]
It is a simple gradient right now change it to something suiting to the theme

**Comment by Sourabh782** [comment]
hii @Rakshit-gen can i contribute to this issue?

**Comment by Rakshit-gen** [comment]
@Sourabh782 Okay work on it we will see how you modify the button

**Comment by Rakshit-gen** [comment]
@Sourabh782 any updates?

**Comment by Rakshit-gen** [comment]
Sure @Sourabh782

**Comment by Sourabh782** [comment]
@Rakshit-gen Can you check this?

![Screenshot 2024-10-03 183009](https://github.com/user-attachments/assets/06036f99-75af-433d-9b96-13d7fb3d9e3f)

![Screenshot 2024-10-03 182958](https://github.com/user-attachments/assets/2a5e1935-5fda-410a-afa0-6b3b11503f80)

I have added 100s transition as well while hovering

**Comment by Rakshit-gen** [comment]
Okay it looks good, can you specify the design changes in the navbar, as they might be hard to find at once

**Comment by Rakshit-gen** [comment]
@Sourabh782 Okay send the pull request mentioning this issue and We will see!
