### ISSUE TITLE
Create a better logo for Slanine

### ISSUE THREAD

**Issue by Rakshit-gen** [Rakshit-gen/Slanine#10]
Make it look classy and cool, you can add it by adding it in the files and changing the layout.tsx.

**Comment by Charul00** [comment]
can you please assign to me

**Comment by Rakshit-gen** [comment]
Assigned to you both the issues @Charul00

**Comment by Rakshit-gen** [comment]
Any update @Charul00 ?

**Comment by coderKrysio** [comment]
@Rakshit-gen do you have any specific design in mind that you want?

**Comment by Rakshit-gen** [comment]
I don't have any as of now @coderKrysio but a black circular logo with S in between and maybe a bit simple but classy type.
You can use any software to build it

**Comment by coderKrysio** [comment]
okay I will make a draft with the above description and will attach it here
if you find it suitable then you can assign me this issue

**Comment by Rakshit-gen** [comment]
@coderKrysio sure that will be great!

**Comment by coderKrysio** [comment]
hey @Rakshit-gen 
![saline](https://github.com/user-attachments/assets/740ba044-42da-4379-980a-da31ffbd5c67)
this is the first draft I came up with
if you any modifications, let me know

**Comment by Rakshit-gen** [comment]
Ohh this one looks good actually!
If you can add a little shine I'll like to see that @coderKrysio

**Comment by coderKrysio** [comment]
![saline (1)](https://github.com/user-attachments/assets/6b02ac5f-526c-403d-8e63-5a444b000d31)
second draft

**Comment by Rakshit-gen** [comment]
Let's go with the first one @coderKrysio , it looks better
I assigned the issue to you, save the icon as a ico file or convert it into one.
Name it favicon.ico and update it in the local repo in the public folder.

**Comment by coderKrysio** [comment]
should I remove the background first as it is set to #000?

**Comment by Rakshit-gen** [comment]
Sure you can do it! Set it to something more appropriate,
If you modify the landing page components too then will rate the pr a level 3.

**Comment by coderKrysio** [comment]
hey @Rakshit-gen 
i have finished all the other two changes on homepage but just want a confirmation on the favicon
which one do you thing is the best to go

![Screenshot 2024-10-09 163704](https://github.com/user-attachments/assets/39bf67cb-3938-4f7f-a7e1-c077a4475b43)
![Screenshot 2024-10-09 163551](https://github.com/user-attachments/assets/245f35be-dff1-4bad-b5d8-598d0825a7eb)

**Comment by Rakshit-gen** [comment]
The first one I will say @coderKrysio
