### ISSUE TITLE
 Add Event Networking Assistant Feature to Prompt Apps

### ISSUE THREAD

**Issue by amitb0ra** [Rakshit-gen/Slanine#106]
I would like to see an event networking assistant feature integrated into the prompt apps. This feature would:

- Help users connect with others at events based on shared interests and goals.
- Suggest conversation starters based on common interests.
- Provide a platform for scheduling meetings or follow-ups.

### Labels
Please assign me under GSSoC'24 ext and hacktoberfest labels.

**Comment by Rakshit-gen** [comment]
Assigned to you @amitb0ra

**Comment by amitb0ra** [comment]
> Assigned to you @amitb0ra

@Rakshit-gen can you give level 3? as its new feature also review my PR please
