### ISSUE TITLE
Fix: the main page responsiveness

### ISSUE THREAD

**Issue by AE-Hertz** [Rakshit-gen/Slanine#126]
Check attachment, I will make the section responsive by fixing the misalignments. As right now it's not looking good so I will fix it.

![Screenshot_2024-10-27-02-08-26-21_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/e73cc7d9-09ce-4f7c-87b4-3b1ea01ed422)

Assign me .

**Comment by Rakshit-gen** [comment]
Assigning this to you
