### ISSUE TITLE
Too much space on the end of the page

### ISSUE THREAD

**Issue by Rakshit-gen** [Rakshit-gen/Slanine#14]
![image](https://github.com/user-attachments/assets/705b4f32-20fb-4d4a-9638-41c23fab004a)

Can be fixed by fixing the MovingCards components.

**Comment by CodingWithError** [comment]
hey @Rakshit-gen can you assign this to me and provide me a bit more details

**Comment by Sourabh782** [comment]
Is this issue free @Rakshit-gen ? if yes, i wanna work on it

**Comment by Rakshit-gen** [comment]
Sure Assigning you @Sourabh782
