### ISSUE TITLE
Add “Ideas That Changed the World” Exploration Feature

### ISSUE THREAD

**Issue by amitb0ra** [Rakshit-gen/Slanine#148]
I would like to see an “Ideas That Changed the World” exploration feature integrated into the prompt apps. This feature would:

- Present users with a significant historical idea each day, like democracy, evolution, or zero.
- Include an interactive timeline showing related discoveries and changes inspired by each idea.
- Offer prompts to reflect on the relevance of these ideas in modern life.
- Encourage users to consider how these groundbreaking concepts impact their own perspectives.

**Please assign me under GSSoC'24 ext and hacktoberfest labels.**

**Comment by Rakshit-gen** [comment]
@amitb0ra 

It will be way better if you send a single Level3 pr for the templates introducing them. As at this point you are just spamming them into my repository.

Either send them in sets of 6 or 7 with a level3 pr each.
Or I'll have to add it to wont fix

**Comment by amitb0ra** [comment]
> @amitb0ra
> 
> It will be way better if you send a single Level3 pr for the templates introducing them. As at this point you are just spamming them into my repository.
> 
> Either send them in sets of 6 or 7 with a level3 pr each. Or I'll have to add it to wont fix

ah, actually all of them are different so for your choice i send them separately. 
do you want that i will propose list of ideas (around 10) and you will select out of them(3-5) at level 3?

**Comment by amitb0ra** [comment]
@Rakshit-gen any update?
