### ISSUE TITLE
Improve billings page

### ISSUE THREAD

**Issue by Rakshit-gen** [Rakshit-gen/Slanine#2]
Add a better background and design to the billings page.
Make it look beautiful and still matching with the theme of the website

**Comment by Itachii27** [comment]
Hi @Rakshit-gen I want to work on this issue. Kindly assign this issue to me

**Comment by Rakshit-gen** [comment]
Sure @Itachii27 tell your workflow and how will you do it

**Comment by Sourabh782** [comment]
hii @Rakshit-gen can i work on it?
my approach: 
![Screenshot 2024-10-03 191952](https://github.com/user-attachments/assets/328188f7-0afc-44e1-9a3b-c7382b159fde)
1. Changing these areas ( colour of upgrade and credits part, improving ui of join membership at top)
2. adding space themed background like in landing page

**Comment by Rakshit-gen** [comment]
Okay @Sourabh782 do show me the changes before sending the PR.
Can you improvise the overall dashboard to look cooler, if yes I will mark the PR as a level 3.

**Comment by Sourabh782** [comment]
thanks @Rakshit-gen, if u dont mind ill submit it till monday? actually have exams on weekends so

**Comment by Rakshit-gen** [comment]
Sure @Sourabh782 take your time!

**Comment by Sourabh782** [comment]
On it

**Comment by Rakshit-gen** [comment]
@all-contributors please add @Sourabh782  for contribution

**Comment by Rakshit-gen** [comment]
@all-contributors please add @Sourabh782 for code

**Comment by Rakshit-gen** [comment]
@all-contributors please add @Sourabh782 for code

**Comment by Sourabh782** [comment]
@Rakshit-gen i was working on the improvement part, but its already closed?
