### ISSUE TITLE
Improve Card Visibility in Dark Mode and Enhance Grid Layout

### ISSUE THREAD

**Issue by manthanmk66** [Rakshit-gen/Slanine#20]
1) The card text and background do not have enough contrast, making the content difficult to read in Dark Mode.
2) The cards lack engaging content, which affects the overall user experience.
![image](https://github.com/user-attachments/assets/e9b68b1c-9221-499c-8fe3-bce77ed511b4)

**Comment by Rakshit-gen** [comment]
There's a similar issue in #18
You can fix that @manthanmk66
