### ISSUE TITLE
Dark mode toggle improvements

### ISSUE THREAD

**Issue by Sourabh782** [Rakshit-gen/Slanine#25]
I wanna work on dark mode toggle improvement.

Current: 
![Screenshot 2024-10-05 080533](https://github.com/user-attachments/assets/16e01ac6-0bbf-4662-8289-5e1a64903ef0)

Problem: Its adding an extra step to select theme option from drop down.

My view: If someone is clicking theme toggle button, then its obvious he want to change the theme of the app. And for the system setting part, what we can do is to set default theme as system defined

My working: Adding default theme as system default, and just switching theme on theme change click.

**Comment by Rakshit-gen** [comment]
Okay that can be implemented would like to check it out! Sure go on @Sourabh782

**Comment by Sourabh782** [comment]
Thanks @Rakshit-gen 👍, working on it
