### ISSUE TITLE
Add history section

### ISSUE THREAD

**Issue by Rakshit-gen** [Rakshit-gen/Slanine#3]
Go to app>dashboard>history>page.tsx
Add a history section for users to see their previously used prompts and answers along with the respective lengths of the AI Responsem

**Comment by Itachii27** [comment]
Hi @Rakshit-gen I want to work on this issue. Kindly assign this issue to me

**Comment by Swetabh333** [comment]
@Rakshit-gen  I'd like to work on this, correct me on this but I think we can get the user with getUser and fetch all the ai response fields for that particular user from the database and display it on the history page?

**Comment by Rakshit-gen** [comment]
Okay @Swetabh333 your approach seems approriate, I am assigning the issue to you!

**Comment by Swetabh333** [comment]
For setting up the database I need to sign up and get the db url from neon right?

**Comment by Rakshit-gen** [comment]
Yes @Swetabh333 you need to put the db urI into your .env file locally

**Comment by Swetabh333** [comment]
@Rakshit-gen there seems to be more dependencies , I have to set up redis as well?

**Comment by Rakshit-gen** [comment]
@Swetabh333 I have put a dummy env file in the readme.md Maybe redis isnt there I will fix it. You need to setup redis too

**Comment by Swetabh333** [comment]
@Rakshit-gen yes the env file does not mention redis, I'll set it up as well I'm assuming you used upstash for it.Thanks for helping out.

**Comment by Rakshit-gen** [comment]
Yes upstash for this project. No problem @Swetabh333

**Comment by Rakshit-gen** [comment]
@Swetabh333 I updated the Readme now you can see!

**Comment by Swetabh333** [comment]
@Rakshit-gen great, I got it working locally, I'll start working on it now

**Comment by Rakshit-gen** [comment]
Okay update me @Swetabh333

**Comment by Swetabh333** [comment]
@Rakshit-gen there already seems to be some boilerplate in history/page.tsx should I remove it or work with it?

**Comment by Swetabh333** [comment]
@Rakshit-gen radix does not seem to have a card component for ui is it alright if I use another Library?

**Comment by Rakshit-gen** [comment]
@Swetabh333 sure you can use shadcn or anything else too
Just make sure it doesn't break the website.
