### ISSUE TITLE
Unresponsive hero section text in landing page

### ISSUE THREAD

**Issue by PrayanshParmar** [Rakshit-gen/Slanine#31]
![image](https://github.com/user-attachments/assets/93908ba6-c518-4519-998a-a617275f22a1)

Hero section main text is hiding in medium screen size, please let me work on this bug.

**Comment by Rakshit-gen** [comment]
Okay assigning this to you @PrayanshParmar

**Comment by PrayanshParmar** [comment]
I have fixed this issue @Rakshit-gen
