### ISSUE TITLE
Database credentials leaked

### ISSUE THREAD

**Issue by PrayanshParmar** [Rakshit-gen/Slanine#36]
![image](https://github.com/user-attachments/assets/4015d0c3-ed30-422c-8cb9-11332d3f2687)
Database credential leaked in drizzle.config.js

**Comment by Rakshit-gen** [comment]
Fix that @PrayanshParmar

**Comment by Rakshit-gen** [comment]
Assigning it to you

**Comment by PrayanshParmar** [comment]
Fixed the issue.
