### ISSUE TITLE
Unresponsive dashboard page card layout

### ISSUE THREAD

**Issue by PrayanshParmar** [Rakshit-gen/Slanine#39]
![image](https://github.com/user-attachments/assets/6e2efe17-fe08-4f4b-bad9-0053e20ca602)
I will fix cards layout for all screen size. Please asssign me this task.

**Comment by Rakshit-gen** [comment]
Card layout is already good, @PrayanshParmar you don't need to change it

**Comment by PrayanshParmar** [comment]
Okay, then if you need any other feature I can help please give me some more task
