### ISSUE TITLE
Improve the UI of Dashboard page

### ISSUE THREAD

**Issue by Rakshit-gen** [Rakshit-gen/Slanine#4]
Looking forward for different ideas and UI tools to change the UI for the dashboard page.

Inform me if you find any good ideas!

Current UI:
![image](https://github.com/user-attachments/assets/43c6ad99-073b-4d67-b673-b02a2b2515c8)

**Comment by Itachii27** [comment]
Hi @Rakshit-gen I want to work on this issue. Kindly assign this issue to me

**Comment by Itachii27** [comment]
Hi @Rakshit-gen I want to work on this issue. Kindly assign this issue to me

**Comment by Rakshit-gen** [comment]
Assigned @Itachii27

**Comment by Rakshit-gen** [comment]
Any updates @Itachii27

**Comment by vidhvath28** [comment]
@Rakshit-gen if this issue is still open , I would like to work on it, I have already setup the project in my local machine so once you confirm I will start working on it.

**Comment by Rakshit-gen** [comment]
Sure @vidhvath28 Assigning it to you!

**Comment by vidhvath28** [comment]
Thank you so much , I have started working on it.

**Comment by Rakshit-gen** [comment]
Okay @vidhvath28 Best of luck!

**Comment by vidhvath28** [comment]
@Rakshit-gen I have submitted the PR , I guess you need to give approval for the  versel deployment so the checks pass.

**Comment by Rakshit-gen** [comment]
Kindly attach images of the work @vidhvath28

**Comment by Sourabh782** [comment]
@Rakshit-gen this issue free?

**Comment by Rakshit-gen** [comment]
Okay! @Sourabh782 , Assigning this to you

**Comment by aasiflm10** [comment]
@Rakshit-gen  can i also work on this issue?

**Comment by Sourabh782** [comment]
It's in progress

**Comment by aasiflm10** [comment]
If for any reason this issue isn't resolved, I would like to work on it. Thanks.

**Comment by Sourabh782** [comment]
@Rakshit-gen can you check card design? 
![image](https://github.com/user-attachments/assets/004114d6-f1f9-44b8-88b8-09bafd6042df)

**Comment by Sourabh782** [comment]
Light mode design: 
![image](https://github.com/user-attachments/assets/122002df-0411-4c09-a636-dee8776ae44c)

Dark mode design:
![Screenshot 2024-10-08 175918](https://github.com/user-attachments/assets/3ddd2e6d-1e11-4d81-a8db-ccfd85338ab1)

@Rakshit-gen

**Comment by Rakshit-gen** [comment]
Okay it looks good @Sourabh782 
Kindly look for any issues and then send the PR.

**Comment by Sourabh782** [comment]
Thanks @Rakshit-gen
