### ISSUE TITLE
Changing the twitter logo to new X logo

### ISSUE THREAD

**Issue by tarunkumar2005** [Rakshit-gen/Slanine#40]
![image](https://github.com/user-attachments/assets/3a1a3841-ceaa-44c2-a8ce-7a4006e68b69)

As the twitter is now X so we need to algin with the advancements and needs to change the logo so @Rakshit-gen Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by Rakshit-gen** [comment]
Okay Assigned this to you! @tarunkumar2005

**Comment by tarunkumar2005** [comment]
@Rakshit-gen Labels are only added i am not assigned to it can you do so also that would be helpful
