### ISSUE TITLE
Bug: Navbar transparency in Light mode and CTA button not displaying properly

### ISSUE THREAD

**Issue by coderKrysio** [Rakshit-gen/Slanine#49]
1. Navbar transparency in Light mode

The landing page UI is not looking good in light mode as the navbar background is set to transparent

**Solution:** Change the background colour

![Screenshot 2024-10-09 105553](https://github.com/user-attachments/assets/77571d05-b59f-4fba-874f-76c618342f39)

2. CTA button not displaying properly

The CTA button is an essential component on the landing page, but here due to its design, it is not making enough impact and is barely visible.

**Solution:** Make the button much larger and impactful while keeping the brand guide and colour palette in consideration

![Screenshot 2024-10-09 105637](https://github.com/user-attachments/assets/a43cd9c3-c75a-4e24-8219-93bdc5ffd87a)

please assign me this issue

**Comment by Rakshit-gen** [comment]
Okay assigning this to you, start working on it @coderKrysio

**Comment by coderKrysio** [comment]
hey @Rakshit-gen, please preview the changes made

https://github.com/user-attachments/assets/75338fec-d5ab-4ea1-9177-bb7a79bf7d68

**Comment by Rakshit-gen** [comment]
It looks great! @coderKrysio 

The UI significantly improved, please solve any errors and send the PR. I'll assign it the points .
