### ISSUE TITLE
Enhance website performance

### ISSUE THREAD

**Issue by Rakshit-gen** [Rakshit-gen/Slanine#54]
Use cleaner and maintainable code to enhance website performance, 
You can use any techniques to do that. Use lazy loading as an example ,
You can use any method to do it. A significant improvement in the website's performance will be appreciated.

**Comment by Sourabh782** [comment]
can i try working on it?

**Comment by Rakshit-gen** [comment]
Sure @Sourabh782 give me a path to implement it and I'll assign it to you

**Comment by Sourabh782** [comment]
so i ran some tests for performance and would like to work on them:
![Screenshot 2024-10-10 102912](https://github.com/user-attachments/assets/5250fdee-c485-44e0-9be4-947fae1e6fc1)
![Screenshot 2024-10-10 102857](https://github.com/user-attachments/assets/c697fb6a-4768-457f-8f02-c22071162bc9)

I can look ways to work around them.
+ many pages have unused imports, so could work on remove them

**Comment by Rakshit-gen** [comment]
Okay and try implementing lazy loading wherever you can @Sourabh782

**Comment by Rakshit-gen** [comment]
Any updates @Sourabh782

**Comment by Sourabh782** [comment]
Yes @Rakshit-gen made some changes will share update till evening, currently in clg

**Comment by Rakshit-gen** [comment]
Okay sure @Sourabh782

**Comment by Sourabh782** [comment]
hii @Rakshit-gen sorry for late reply, see one of the components i implemented lazy loading were of cards in dashboard

https://github.com/user-attachments/assets/b58d1d2e-0f0a-4052-b73e-a95ff4949e31

**Comment by Sourabh782** [comment]
ya from some components, like where i worked in past, exploring other folders

**Comment by Rakshit-gen** [comment]
@Sourabh782 okay let's see how it works, check the performance of the website after rehosting it yourself.

**Comment by Sourabh782** [comment]
ohkk ill check after removing unwanted code

**Comment by Rakshit-gen** [comment]
What kinda issue @Sourabh782 .
Attach the image for it

**Comment by Sourabh782** [comment]
> What kinda issue @Sourabh782 . Attach the image for  it 
while using npm install I have having the issue

**Comment by Rakshit-gen** [comment]
There must be some issues with the packages you are using I have to see what issue is it @Sourabh782

**Comment by Sourabh782** [comment]
@Rakshit-gen 
![image](https://github.com/user-attachments/assets/1c8b3f95-8511-4aba-a2a4-8d3da059f963)

can you check one thing, like clone your repo and just try npm i, are you seeing some error in doing so?

**Comment by Rakshit-gen** [comment]
Okay I'll try once I get free @Sourabh782

**Comment by Rakshit-gen** [comment]
It is not happening for me @Sourabh782

**Comment by Sourabh782** [comment]
@Rakshit-gen 
![Uploading Screenshot 2024-10-17 163346.png…]()

**Comment by Sourabh782** [comment]
hii @Rakshit-gen i got some update

will it work?
![image](https://github.com/user-attachments/assets/6c0dec6d-8dc3-4df1-9b68-84efb3fdf5c9)

**Comment by Rakshit-gen** [comment]
Okay @Sourabh782 this looks good, check for any errors and send the PR

**Comment by Sourabh782** [comment]
> Okay @Sourabh782 this looks good, check for any errors and send the PR

i dont see any error as of now, its working fine, just trying to increase some accesseblity points, then will raise pr

**Comment by Rakshit-gen** [comment]
Okay @Sourabh782 send the PR, I'll merge it after I get a bit of free time, thank you for the contribution!
