### ISSUE TITLE
Improve dark mode icon 

### ISSUE THREAD

**Issue by Nbisht1208** [Rakshit-gen/Slanine#59]
Toggle icon is reversed

![Uploading Screenshot_2024-10-15-10-28-50-890_com.android.chrome.jpg…]()
 

![Screenshot_2024-10-15-10-28-50-890_com android chrome](https://github.com/user-attachments/assets/6bdc0eaa-6ccb-4483-bd02-d5ee19d57e09)

**Comment by Nbisht1208** [comment]
@Rakshit-gen i was saying that when we want to change theme to dark mode toggle button should moon icon but it showing sun which indicate to white mood,So conclusion is the icon is reversed according to the conversion of theme

**Comment by Rakshit-gen** [comment]
It is right, it displays the current theme of the website. @Nbisht1208
