### ISSUE TITLE
Better responsiveness on mobile.

### ISSUE THREAD

**Issue by Rakshit-gen** [Rakshit-gen/Slanine#6]
Currently for each page, responsiveness isn't as good. Just open the project in your phone and go to the billings page as an example.

Please improve the responsiveness for the mobiles devices.

**Comment by Vivek7038** [comment]
can you assign me  @Rakshit-gen 
![image](https://github.com/user-attachments/assets/4d2acd5b-a389-4eb9-a0c9-41b917b4fb08)
will fix these btn alignment , side gap and top nav, will also  fix other pages

**Comment by Rakshit-gen** [comment]
Assigned @Vivek7038

**Comment by Rakshit-gen** [comment]
Any updates @Vivek7038 ?

**Comment by Vivek7038** [comment]
> Any updates @Vivek7038 ?

you can assign these to someone else . I got stuck in some other work

**Comment by Sourabh782** [comment]
@Rakshit-gen  is it open? i wanna contribute

> > Any updates @Vivek7038 ?
> 
> can you can assign these to someone else . I got stuck in some other work

**Comment by Sourabh782** [comment]
@Rakshit-gen  
I want some suggestions

**Comment by Rakshit-gen** [comment]
Sure ask @Sourabh782

**Comment by Sourabh782** [comment]
> Sure ask @Sourabh782

see

**Comment by Rakshit-gen** [comment]
Sure implement it and remove the history button on the front and put the credits used at the button of the hamburger menu only. @Sourabh782

**Comment by Sourabh782** [comment]
> Sure implement it and remove the history button on the front and put the credits used at the button of the hamburger menu only. @Sourabh782

Okk
