### ISSUE TITLE
User Experience Enhancements | BackToTop Button Scrolling is not Smooth

### ISSUE THREAD

**Issue by Shariq2003** [Rakshit-gen/Slanine#60]
https://github.com/user-attachments/assets/42d99e1d-0cdd-4041-9586-35786a1c4be4

The BackToTop button sets the current Y position as 0 making it hard scroll which downgrades UX.

I want to add smooth scrolling by animating the Scrolling by Y value speed variation.

@Rakshit-gen Please assign this to me.

**Comment by Rakshit-gen** [comment]
Okay that's a great idea @Shariq2003 
Assigning the issue to you
