### ISSUE TITLE
Adding FAQ section below Landing Page

### ISSUE THREAD

**Issue by dev129** [Rakshit-gen/Slanine#71]
Hi @Rakshit-gen 
I would like to design the FAQ Section for your amazing website, I can promise that after your assign me the haktoberfest , gssoc-ext and level label I shall provide you the intial design in the next 1 hour and generate the design in the next 24 hours of wireframe approval.

**Comment by Rakshit-gen** [comment]
Okay go on with it! Assigning this to you @dev129

**Comment by dev129** [comment]
![wireframe](https://github.com/user-attachments/assets/442a0a62-dea5-4a8b-8e15-017ae57a19cd)
Hi @Rakshit-gen , this is the perfect wireframe design for your site, if you have another design in mind let me know.

**Comment by Rakshit-gen** [comment]
This looks good enough, implement it for both the themes. You can put basic questions about the website in the questions.

**Comment by dev129** [comment]
That I will for sure.

**Comment by Rakshit-gen** [comment]
Okay @dev129 
Best of luck!

**Comment by dev129** [comment]
https://github.com/user-attachments/assets/cfb0b42f-e48e-4557-9428-74fbb18577b8

Hi @Rakshit-gen , I have made the design, and it is working , do you want any changes else I shall raise the PR .

**Comment by Rakshit-gen** [comment]
This looks good, can you make them have different colors for the dark theme, 
You can raise a PR

**Comment by dev129** [comment]
Okay @Rakshit-gen what colors are you thinking of ?

**Comment by Rakshit-gen** [comment]
You can send the PR, I will manage the themes @dev129

**Comment by dev129** [comment]
Okay

**Comment by dev129** [comment]
Done @Rakshit-gen , please check it
