### ISSUE TITLE
Add Automated Welcome Message for New Issues

### ISSUE THREAD

**Issue by smog-root** [Rakshit-gen/Slanine#76]
**Create a GitHub Actions Workflow:**

- Add a new workflow to .github/workflows/welcome-message.yml.
- Use the actions-ecosystem/action-create-comment action to post a welcome message when an issue is opened.

_**Note**_: i'm expecting a gssoc-ext with level3 (or) level2 and a hacktoberfest-accepted label!

@Rakshit-gen

**Comment by Rakshit-gen** [comment]
Sure assigning this to you @smog-root

**Comment by smog-root** [comment]
i have implemented this issue in #80

make it level3 @Rakshit-gen
