### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [Rakshit-gen/Slanine#79]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @Rakshit-gen 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by Rakshit-gen** [comment]
It's a level 2 issue, I'll award you that
