### ISSUE TITLE
Add Missing Meta Tags, Robots.txt, and Sitemap for Improved SEO

### ISSUE THREAD

**Issue by myselfshivams** [Rakshit-gen/Slanine#8]
The website currently lacks essential SEO elements such as meta tags, robots.txt, and a sitemap. These are critical for optimizing the site’s visibility on search engines and improving overall discoverability.

Proposed Solution:
- Meta Tags: Add relevant meta tags (title, description, keywords, Open Graph, Twitter cards, etc.) to improve SEO and social sharing.
- Robots.txt: Create a robots.txt file to guide web crawlers and define which pages should be indexed.
- Sitemap: Generate an XML sitemap to ensure proper indexing by search engines.

Labels:
- gssoc
- hacktoberfest

@Rakshit-gen Please assign this task to me (myslefshivams).

**Comment by Rakshit-gen** [comment]
Assigned @myselfshivams
